//////////////////////////////////////////////////////////////////////////////
// Name:        Elements_CopyConstructors.cpp
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#include "SVGPathElement.h"
#include "SVGPolygonElement.h"
#include "SVGTextElement.h"
#include "SVGLineElement.h"
#include "SVGEllipseElement.h"
#include "SVGRectElement.h"
#include "SVGPolylineElement.h"
#include "SVGCircleElement.h"
#include "SVGImageElement.h"

// wxSVGPathElement
wxSVGPathElement::wxSVGPathElement(wxSVGPathElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src),
  wxSVGAnimatedPathData(src)
{
  m_pathLength = src.m_pathLength;
  m_canvasItem = NULL;
}

// wxSVGPolygonElement
wxSVGPolygonElement::wxSVGPolygonElement(wxSVGPolygonElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src),
  wxSVGAnimatedPoints(src)
{
  m_canvasItem = NULL;
}

// wxSVGTextElement
wxSVGTextElement::wxSVGTextElement(wxSVGTextElement& src):
  wxSVGTextPositioningElement(src),
  wxSVGTransformable(src)
{
  m_canvasItem = NULL;
}

// wxSVGLineElement
wxSVGLineElement::wxSVGLineElement(wxSVGLineElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src)
{
  m_x1 = src.m_x1;
  m_y1 = src.m_y1;
  m_x2 = src.m_x2;
  m_y2 = src.m_y2;
  m_canvasItem = NULL;
}

// wxSVGEllipseElement
wxSVGEllipseElement::wxSVGEllipseElement(wxSVGEllipseElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src)
{
  m_cx = src.m_cx;
  m_cy = src.m_cy;
  m_rx = src.m_rx;
  m_ry = src.m_ry;
  m_canvasItem = NULL;
}

// wxSVGRectElement
wxSVGRectElement::wxSVGRectElement(wxSVGRectElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src)
{
  m_x = src.m_x;
  m_y = src.m_y;
  m_width = src.m_width;
  m_height = src.m_height;
  m_rx = src.m_rx;
  m_ry = src.m_ry;
  m_canvasItem = NULL;
}

// wxSVGPolylineElement
wxSVGPolylineElement::wxSVGPolylineElement(wxSVGPolylineElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src),
  wxSVGAnimatedPoints(src)
{
  m_canvasItem = NULL;
}

// wxSVGCircleElement
wxSVGCircleElement::wxSVGCircleElement(wxSVGCircleElement& src):
  wxSVGElement(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src)
{
  m_cx = src.m_cx;
  m_cy = src.m_cy;
  m_r = src.m_r;
  m_canvasItem = NULL;
}

// wxSVGImageElement
wxSVGImageElement::wxSVGImageElement(wxSVGImageElement& src):
  wxSVGElement(src),
  wxSVGURIReference(src),
  wxSVGTests(src),
  wxSVGLangSpace(src),
  wxSVGExternalResourcesRequired(src),
  wxSVGStylable(src),
  wxSVGTransformable(src),
  wxEventTarget(src)
{
  m_x = src.m_x;
  m_y = src.m_y;
  m_width = src.m_width;
  m_height = src.m_height;
  m_preserveAspectRatio = src.m_preserveAspectRatio;
  m_canvasItem = NULL;
}

