//////////////////////////////////////////////////////////////////////////////
// Name:        SVGDocument_CreateElement.cpp
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genSvgElement.py
//////////////////////////////////////////////////////////////////////////////

wxXmlElement* wxSVGDocument::CreateElementNS(const wxString& namespaceURI,
  const wxString& qualifiedName)
{
  wxSVGElement* res = NULL;
  if (qualifiedName == wxT("feTurbulence"))
    res = new wxSVGFETurbulenceElement(this);
  else if (qualifiedName == wxT("feGaussianBlur"))
    res = new wxSVGFEGaussianBlurElement(this);
  else if (qualifiedName == wxT("feTile"))
    res = new wxSVGFETileElement(this);
  else if (qualifiedName == wxT("textPath"))
    res = new wxSVGTextPathElement(this);
  else if (qualifiedName == wxT("text"))
    res = new wxSVGTextElement(this);
  else if (qualifiedName == wxT("image"))
    res = new wxSVGImageElement(this);
  else if (qualifiedName == wxT("font-face-uri"))
    res = new wxSVGFontFaceUriElement(this);
  else if (qualifiedName == wxT("missing-glyph"))
    res = new wxSVGMissingGlyphElement(this);
  else if (qualifiedName == wxT("font-face"))
    res = new wxSVGFontFaceElement(this);
  else if (qualifiedName == wxT("set"))
    res = new wxSVGSetElement(this);
  else if (qualifiedName == wxT("polyline"))
    res = new wxSVGPolylineElement(this);
  else if (qualifiedName == wxT("hkern"))
    res = new wxSVGHKernElement(this);
  else if (qualifiedName == wxT("marker"))
    res = new wxSVGMarkerElement(this);
  else if (qualifiedName == wxT("altGlyph"))
    res = new wxSVGAltGlyphElement(this);
  else if (qualifiedName == wxT("animate"))
    res = new wxSVGAnimateElement(this);
  else if (qualifiedName == wxT("font"))
    res = new wxSVGFontElement(this);
  else if (qualifiedName == wxT("color-profile"))
    res = new wxSVGColorProfileElement(this);
  else if (qualifiedName == wxT("ellipse"))
    res = new wxSVGEllipseElement(this);
  else if (qualifiedName == wxT("mpath"))
    res = new wxSVGMPathElement(this);
  else if (qualifiedName == wxT("cursor"))
    res = new wxSVGCursorElement(this);
  else if (qualifiedName == wxT("use"))
    res = new wxSVGUseElement(this);
  else if (qualifiedName == wxT("font-face-src"))
    res = new wxSVGFontFaceSrcElement(this);
  else if (qualifiedName == wxT("polygon"))
    res = new wxSVGPolygonElement(this);
  else if (qualifiedName == wxT("title"))
    res = new wxSVGTitleElement(this);
  else if (qualifiedName == wxT("definition-src"))
    res = new wxSVGDefinitionSrcElement(this);
  else if (qualifiedName == wxT("tspan"))
    res = new wxSVGTSpanElement(this);
  else if (qualifiedName == wxT("feFlood"))
    res = new wxSVGFEFloodElement(this);
  else if (qualifiedName == wxT("feBlend"))
    res = new wxSVGFEBlendElement(this);
  else if (qualifiedName == wxT("vkern"))
    res = new wxSVGVKernElement(this);
  else if (qualifiedName == wxT("feSpecularLighting"))
    res = new wxSVGFESpecularLightingElement(this);
  else if (qualifiedName == wxT("feColorMatrix"))
    res = new wxSVGFEColorMatrixElement(this);
  else if (qualifiedName == wxT("feImage"))
    res = new wxSVGFEImageElement(this);
  else if (qualifiedName == wxT("circle"))
    res = new wxSVGCircleElement(this);
  else if (qualifiedName == wxT("radialGradient"))
    res = new wxSVGRadialGradientElement(this);
  else if (qualifiedName == wxT("glyphRef"))
    res = new wxSVGGlyphRefElement(this);
  else if (qualifiedName == wxT("metadata"))
    res = new wxSVGMetadataElement(this);
  else if (qualifiedName == wxT("defs"))
    res = new wxSVGDefsElement(this);
  else if (qualifiedName == wxT("feFuncA"))
    res = new wxSVGFEFuncAElement(this);
  else if (qualifiedName == wxT("feFuncB"))
    res = new wxSVGFEFuncBElement(this);
  else if (qualifiedName == wxT("font-face-name"))
    res = new wxSVGFontFaceNameElement(this);
  else if (qualifiedName == wxT("fePointLight"))
    res = new wxSVGFEPointLightElement(this);
  else if (qualifiedName == wxT("feSpotLight"))
    res = new wxSVGFESpotLightElement(this);
  else if (qualifiedName == wxT("feFuncG"))
    res = new wxSVGFEFuncGElement(this);
  else if (qualifiedName == wxT("feConvolveMatrix"))
    res = new wxSVGFEConvolveMatrixElement(this);
  else if (qualifiedName == wxT("feDistantLight"))
    res = new wxSVGFEDistantLightElement(this);
  else if (qualifiedName == wxT("symbol"))
    res = new wxSVGSymbolElement(this);
  else if (qualifiedName == wxT("clipPath"))
    res = new wxSVGClipPathElement(this);
  else if (qualifiedName == wxT("stop"))
    res = new wxSVGStopElement(this);
  else if (qualifiedName == wxT("style"))
    res = new wxSVGStyleElement(this);
  else if (qualifiedName == wxT("animateColor"))
    res = new wxSVGAnimateColorElement(this);
  else if (qualifiedName == wxT("feDisplacementMap"))
    res = new wxSVGFEDisplacementMapElement(this);
  else if (qualifiedName == wxT("feFuncR"))
    res = new wxSVGFEFuncRElement(this);
  else if (qualifiedName == wxT("glyph"))
    res = new wxSVGGlyphElement(this);
  else if (qualifiedName == wxT("a"))
    res = new wxSVGAElement(this);
  else if (qualifiedName == wxT("feComposite"))
    res = new wxSVGFECompositeElement(this);
  else if (qualifiedName == wxT("foreignObject"))
    res = new wxSVGForeignObjectElement(this);
  else if (qualifiedName == wxT("path"))
    res = new wxSVGPathElement(this);
  else if (qualifiedName == wxT("line"))
    res = new wxSVGLineElement(this);
  else if (qualifiedName == wxT("rect"))
    res = new wxSVGRectElement(this);
  else if (qualifiedName == wxT("desc"))
    res = new wxSVGDescElement(this);
  else if (qualifiedName == wxT("altGlyphItem"))
    res = new wxSVGAltGlyphItemElement(this);
  else if (qualifiedName == wxT("feComponentTransfer"))
    res = new wxSVGFEComponentTransferElement(this);
  else if (qualifiedName == wxT("g"))
    res = new wxSVGGElement(this);
  else if (qualifiedName == wxT("feMorphology"))
    res = new wxSVGFEMorphologyElement(this);
  else if (qualifiedName == wxT("animateMotion"))
    res = new wxSVGAnimateMotionElement(this);
  else if (qualifiedName == wxT("svg"))
    res = new wxSVGSVGElement(this);
  else if (qualifiedName == wxT("feDiffuseLighting"))
    res = new wxSVGFEDiffuseLightingElement(this);
  else if (qualifiedName == wxT("script"))
    res = new wxSVGScriptElement(this);
  else if (qualifiedName == wxT("mask"))
    res = new wxSVGMaskElement(this);
  else if (qualifiedName == wxT("altGlyphDef"))
    res = new wxSVGAltGlyphDefElement(this);
  else if (qualifiedName == wxT("tref"))
    res = new wxSVGTRefElement(this);
  else if (qualifiedName == wxT("filter"))
    res = new wxSVGFilterElement(this);
  else if (qualifiedName == wxT("font-face-format"))
    res = new wxSVGFontFaceFormatElement(this);
  else if (qualifiedName == wxT("switch"))
    res = new wxSVGSwitchElement(this);
  else if (qualifiedName == wxT("animateTransform"))
    res = new wxSVGAnimateTransformElement(this);
  else if (qualifiedName == wxT("linearGradient"))
    res = new wxSVGLinearGradientElement(this);
  else if (qualifiedName == wxT("feOffset"))
    res = new wxSVGFEOffsetElement(this);
  else if (qualifiedName == wxT("pattern"))
    res = new wxSVGPatternElement(this);
  else if (qualifiedName == wxT("feMerge"))
    res = new wxSVGFEMergeElement(this);
  else if (qualifiedName == wxT("view"))
    res = new wxSVGViewElement(this);
  else if (qualifiedName == wxT("feMergeNode"))
    res = new wxSVGFEMergeNodeElement(this);
  else 
  {
  }
  return res;
}
