//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPathSegList.cpp
// Author:      Alex Thuering
// Created:     2005/09/27
// RCS-ID:      $Id: SVGPathSegList.cpp,v 1.2 2005-09-29 09:59:24 ntalex Exp $
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genList.py
//////////////////////////////////////////////////////////////////////////////

#include "SVGPathSegList.h"
#include "SVGPathSegClosePath.h"
#include "SVGPathSegMovetoAbs.h"
#include "SVGPathSegMovetoRel.h"
#include "SVGPathSegLinetoAbs.h"
#include "SVGPathSegLinetoRel.h"
#include "SVGPathSegCurvetoCubicAbs.h"
#include "SVGPathSegCurvetoCubicRel.h"
#include "SVGPathSegCurvetoQuadraticAbs.h"
#include "SVGPathSegCurvetoQuadraticRel.h"
#include "SVGPathSegArcAbs.h"
#include "SVGPathSegArcRel.h"
#include "SVGPathSegLinetoHorizontalAbs.h"
#include "SVGPathSegLinetoHorizontalRel.h"
#include "SVGPathSegLinetoVerticalAbs.h"
#include "SVGPathSegLinetoVerticalRel.h"
#include "SVGPathSegCurvetoCubicSmoothAbs.h"
#include "SVGPathSegCurvetoCubicSmoothRel.h"
#include "SVGPathSegCurvetoQuadraticSmoothAbs.h"
#include "SVGPathSegCurvetoQuadraticSmoothRel.h"


#include <wx/arrimpl.cpp>
WX_DEFINE_OBJARRAY(wxSVGPathSegListBase);

void wxSVGPathSegList::DoCopy(const wxSVGPathSegList& src)
{
  for (int i=0; i<(int)src.Count(); i++)
  {
    switch (src[i].GetPathSegType())
	{
	  case wxPATHSEG_MOVETO_ABS:
        Add(new wxSVGPathSegMovetoAbs((const wxSVGPathSegMovetoAbs&)src[i]));
        break;
	  case wxPATHSEG_MOVETO_REL:
        Add(new wxSVGPathSegMovetoRel((const wxSVGPathSegMovetoRel&)src[i]));
        break;
	  case wxPATHSEG_LINETO_ABS:
        Add(new wxSVGPathSegLinetoAbs((const wxSVGPathSegLinetoAbs&)src[i]));
        break;
	  case wxPATHSEG_LINETO_REL:
        Add(new wxSVGPathSegLinetoRel((const wxSVGPathSegLinetoRel&)src[i]));
        break;
	  case wxPATHSEG_LINETO_HORIZONTAL_ABS:
        Add(new wxSVGPathSegLinetoHorizontalAbs((const wxSVGPathSegLinetoHorizontalAbs&)src[i]));
        break;
	  case wxPATHSEG_LINETO_HORIZONTAL_REL:
        Add(new wxSVGPathSegLinetoHorizontalRel((const wxSVGPathSegLinetoHorizontalRel&)src[i]));
        break;
	  case wxPATHSEG_LINETO_VERTICAL_ABS:
        Add(new wxSVGPathSegLinetoVerticalAbs((const wxSVGPathSegLinetoVerticalAbs&)src[i]));
        break;
	  case wxPATHSEG_LINETO_VERTICAL_REL:
        Add(new wxSVGPathSegLinetoVerticalRel((const wxSVGPathSegLinetoVerticalRel&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_CUBIC_ABS:
        Add(new wxSVGPathSegCurvetoCubicAbs((const wxSVGPathSegCurvetoCubicAbs&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_CUBIC_REL:
        Add(new wxSVGPathSegCurvetoCubicRel((const wxSVGPathSegCurvetoCubicRel&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_CUBIC_SMOOTH_ABS:
        Add(new wxSVGPathSegCurvetoCubicSmoothAbs((const wxSVGPathSegCurvetoCubicSmoothAbs&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_CUBIC_SMOOTH_REL:
        Add(new wxSVGPathSegCurvetoCubicSmoothRel((const wxSVGPathSegCurvetoCubicSmoothRel&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_QUADRATIC_ABS:
        Add(new wxSVGPathSegCurvetoQuadraticAbs((const wxSVGPathSegCurvetoQuadraticAbs&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_QUADRATIC_REL:
        Add(new wxSVGPathSegCurvetoQuadraticRel((const wxSVGPathSegCurvetoQuadraticRel&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_QUADRATIC_SMOOTH_ABS:
        Add(new wxSVGPathSegCurvetoQuadraticSmoothAbs((const wxSVGPathSegCurvetoQuadraticSmoothAbs&)src[i]));
        break;
	  case wxPATHSEG_CURVETO_QUADRATIC_SMOOTH_REL:
        Add(new wxSVGPathSegCurvetoQuadraticSmoothRel((const wxSVGPathSegCurvetoQuadraticSmoothRel&)src[i]));
        break;
	  case wxPATHSEG_ARC_ABS:
        Add(new wxSVGPathSegArcAbs((const wxSVGPathSegArcAbs&)src[i]));
        break;
	  case wxPATHSEG_ARC_REL:
        Add(new wxSVGPathSegArcRel((const wxSVGPathSegArcRel&)src[i]));
        break;
	  case wxPATHSEG_CLOSEPATH:
        Add(new wxSVGPathSegClosePath((const wxSVGPathSegClosePath&)src[i]));
		break;
	  case wxPATHSEG_UNKNOWN:
		break;
	}
  }
}
