//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPointList.cpp
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genList.py
//////////////////////////////////////////////////////////////////////////////

#include "SVGPointList.h"
#include <wx/arrimpl.cpp>
WX_DEFINE_OBJARRAY(wxSVGPointList);
