//////////////////////////////////////////////////////////////////////////////
// Name:        CSSStyleDeclaration_styles.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genCSS.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_CSS_STYLE_DECLARATION__STYLES_H
#define WX_CSS_STYLE_DECLARATION__STYLES_H


wxString s_cssPropertys[] = 
{
  wxT("clip-path"),
  wxT("color"),
  wxT("display"),
  wxT("fill"),
  wxT("fill-opacity"),
  wxT("fill-rule"),
  wxT("filter"),
  wxT("font-family"),
  wxT("font-size"),
  wxT("font-stretch"),
  wxT("font-style"),
  wxT("font-variant"),
  wxT("font-weight"),
  wxT("marker"),
  wxT("marker-end"),
  wxT("marker-mid"),
  wxT("marker-start"),
  wxT("opacity"),
  wxT("stop-color"),
  wxT("stop-opacity"),
  wxT("stroke"),
  wxT("stroke-dashoffset"),
  wxT("stroke-linecap"),
  wxT("stroke-linejoin"),
  wxT("stroke-miterlimit"),
  wxT("stroke-opacity"),
  wxT("stroke-width"),
  wxT("text-anchor"),
  wxT("visibility")
};
    

#endif // WX_CSS_STYLE_DECLARATION__STYLES_H
