//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedLengthList.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_LENGTH_LIST_H
#define WX_SVG_ANIMATED_LENGTH_LIST_H

#include "Animated.h"
#include "SVGLengthList.h"

WXSVG_MAKE_ANIMATED(LengthList, wxSVGLengthList)

#endif // WX_SVG_ANIMATED_LENGTH_LIST_H
