//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedRect.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_RECT_H
#define WX_SVG_ANIMATED_RECT_H

#include "Animated.h"
#include "SVGRect.h"

WXSVG_MAKE_ANIMATED(Rect, wxSVGRect)

#endif // WX_SVG_ANIMATED_RECT_H
