//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedString.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_STRING_H
#define WX_SVG_ANIMATED_STRING_H

#include "Animated.h"

WXSVG_MAKE_ANIMATED(String, wxString)

#endif // WX_SVG_ANIMATED_STRING_H
