//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedPreserveAspectRatio.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_PRESERVE_ASPECT_RATIO_H
#define WX_SVG_ANIMATED_PRESERVE_ASPECT_RATIO_H

#include "Animated.h"
#include "SVGPreserveAspectRatio.h"

WXSVG_MAKE_ANIMATED(PreserveAspectRatio, wxSVGPreserveAspectRatio)

#endif // WX_SVG_ANIMATED_PRESERVE_ASPECT_RATIO_H
