//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimateColorElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATE_COLOR_ELEMENT_H
#define WX_SVG_ANIMATE_COLOR_ELEMENT_H

#include "SVGAnimationElement.h"
#include "String.h"

class wxSVGAnimateColorElement:
  public wxSVGAnimationElement
{
  public:
    wxSVGAnimateColorElement(wxSVGDocument* doc, wxString tagName = wxT("animateColor")):
      wxSVGAnimationElement(doc, tagName) {}
    virtual ~wxSVGAnimateColorElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_ANIMATECOLOR_ELEMENT; }
};

#endif // WX_SVG_ANIMATE_COLOR_ELEMENT_H
