//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedEnumeration.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_ENUMERATION_H
#define WX_SVG_ANIMATED_ENUMERATION_H

#include "Animated.h"

WXSVG_MAKE_ANIMATED_NUMBER(Enumeration, char)

#endif // WX_SVG_ANIMATED_ENUMERATION_H
