//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimatedNumberList.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genAnimated.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATED_NUMBER_LIST_H
#define WX_SVG_ANIMATED_NUMBER_LIST_H

#include "Animated.h"
#include "SVGNumberList.h"

WXSVG_MAKE_ANIMATED(NumberList, wxSVGNumberList)

#endif // WX_SVG_ANIMATED_NUMBER_LIST_H
