//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAnimateElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ANIMATE_ELEMENT_H
#define WX_SVG_ANIMATE_ELEMENT_H

#include "SVGAnimationElement.h"
#include "String.h"

class wxSVGAnimateElement:
  public wxSVGAnimationElement
{
  public:
    wxSVGAnimateElement(wxSVGDocument* doc, wxString tagName = wxT("animate")):
      wxSVGAnimationElement(doc, tagName) {}
    virtual ~wxSVGAnimateElement() {}
    wxXmlNode* CloneNode(bool deep = true) { return new wxSVGAnimateElement(*this); }
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_ANIMATE_ELEMENT; }
};

#endif // WX_SVG_ANIMATE_ELEMENT_H
