//////////////////////////////////////////////////////////////////////////////
// Name:        SVGClipPathElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_CLIP_PATH_ELEMENT_H
#define WX_SVG_CLIP_PATH_ELEMENT_H

#include "SVGElement.h"
#include "SVGTests.h"
#include "SVGLangSpace.h"
#include "SVGExternalResourcesRequired.h"
#include "SVGStylable.h"
#include "SVGTransformable.h"
#include "SVGUnitTypes.h"
#include "SVGAnimatedEnumeration.h"
#include "String.h"

class wxSVGClipPathElement:
  public wxSVGElement,
  public wxSVGTests,
  public wxSVGLangSpace,
  public wxSVGExternalResourcesRequired,
  public wxSVGStylable,
  public wxSVGTransformable,
  public wxSVGUnitTypes
{
  protected:
    wxSVGAnimatedEnumeration m_clipPathUnits;

  public:
    inline char GetClipPathUnits() const { return m_clipPathUnits.GetBaseVal(); }
    inline void SetClipPathUnits(const char n) { m_clipPathUnits.GetBaseVal() = n; }

  public:
    inline char GetAnimatedClipPathUnits() const { return m_clipPathUnits.GetAnimVal(); }
    inline void SetAnimatedClipPathUnits(const char n) { m_clipPathUnits.GetAnimVal() = n; }

  public:
    wxSVGClipPathElement(wxSVGDocument* doc, wxString tagName = wxT("clipPath")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGClipPathElement() {}
    wxXmlNode* CloneNode(bool deep = true) { return new wxSVGClipPathElement(*this); }
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_CLIPPATH_ELEMENT; }
};

#endif // WX_SVG_CLIP_PATH_ELEMENT_H
