//////////////////////////////////////////////////////////////////////////////
// Name:        SVGColor.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_COLOR_H
#define WX_SVG_COLOR_H

#include "CSSValue.h"
#include "RGBColor.h"
#include "SVGICCColor.h"
#include "String.h"

class wxSVGColor:
  public wxCSSValue
{
  public:

	enum wxSVG_COLORTYPE
	{
	  wxSVG_COLORTYPE_UNKNOWN = 0,
	  wxSVG_COLORTYPE_RGBCOLOR = 1,
	  wxSVG_COLORTYPE_RGBCOLOR_ICCCOLOR = 2,
	  wxSVG_COLORTYPE_CURRENTCOLOR = 3
	};

  protected:
	wxSVG_COLORTYPE m_colorType;
	wxRGBColor m_rgbColor;
	wxSVGICCColor m_iccColor;

  public:
	inline wxSVG_COLORTYPE GetColorType() const { return m_colorType; }
	inline void SetColorType(const wxSVG_COLORTYPE& n) { m_colorType = n; }

	inline wxRGBColor GetRgbColor() const { return m_rgbColor; }
	inline void SetRgbColor(const wxRGBColor& n) { m_rgbColor = n; }

	inline wxSVGICCColor& GetIccColor() { return m_iccColor; }
	inline void SetIccColor(const wxSVGICCColor& n) { m_iccColor = n; }

  public:
	wxSVGColor(): m_colorType(wxSVG_COLORTYPE(0)) {}
	virtual ~wxSVGColor() {}
	virtual void SetRGBColor(const wxString& rgbColor);
	virtual void SetRGBColorICCColor(const wxString& rgbColor, const wxString& iccColor);
	virtual void SetColor(wxSVG_COLORTYPE colorType, const wxString& rgbColor, const wxString& iccColor);
};

#endif // WX_SVG_COLOR_H
