//////////////////////////////////////////////////////////////////////////////
// Name:        SVGDefinitionSrcElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_DEFINITION_SRC_ELEMENT_H
#define WX_SVG_DEFINITION_SRC_ELEMENT_H

#include "SVGElement.h"
#include "String.h"

class wxSVGDefinitionSrcElement:
  public wxSVGElement
{
  public:
	wxSVGDefinitionSrcElement(wxSVGDocument* doc, wxString tagName = wxT("definition-src")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGDefinitionSrcElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_DEFINITION_SRC_ELEMENT; }
};

#endif // WX_SVG_DEFINITION_SRC_ELEMENT_H
