//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFilterElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FILTER_ELEMENT_H
#define WX_SVG_FILTER_ELEMENT_H

#include "SVGElement.h"
#include "SVGURIReference.h"
#include "SVGLangSpace.h"
#include "SVGExternalResourcesRequired.h"
#include "SVGStylable.h"
#include "SVGUnitTypes.h"
#include "SVGAnimatedEnumeration.h"
#include "SVGAnimatedLength.h"
#include "SVGAnimatedInteger.h"
#include "String.h"

class wxSVGFilterElement:
  public wxSVGElement,
  public wxSVGURIReference,
  public wxSVGLangSpace,
  public wxSVGExternalResourcesRequired,
  public wxSVGStylable,
  public wxSVGUnitTypes
{
  protected:
    wxSVGAnimatedEnumeration m_filterUnits;
    wxSVGAnimatedEnumeration m_primitiveUnits;
    wxSVGAnimatedLength m_x;
    wxSVGAnimatedLength m_y;
    wxSVGAnimatedLength m_width;
    wxSVGAnimatedLength m_height;
    wxSVGAnimatedInteger m_filterResX;
    wxSVGAnimatedInteger m_filterResY;

  public:
    inline char GetFilterUnits() const { return m_filterUnits.GetBaseVal(); }
    inline void SetFilterUnits(const char n) { m_filterUnits.GetBaseVal() = n; }

    inline char GetPrimitiveUnits() const { return m_primitiveUnits.GetBaseVal(); }
    inline void SetPrimitiveUnits(const char n) { m_primitiveUnits.GetBaseVal() = n; }

    inline wxSVGLength& GetX() { return m_x.GetBaseVal(); }
    inline void SetX(const wxSVGLength& n) { m_x.GetBaseVal() = n; }

    inline wxSVGLength& GetY() { return m_y.GetBaseVal(); }
    inline void SetY(const wxSVGLength& n) { m_y.GetBaseVal() = n; }

    inline wxSVGLength& GetWidth() { return m_width.GetBaseVal(); }
    inline void SetWidth(const wxSVGLength& n) { m_width.GetBaseVal() = n; }

    inline wxSVGLength& GetHeight() { return m_height.GetBaseVal(); }
    inline void SetHeight(const wxSVGLength& n) { m_height.GetBaseVal() = n; }

    inline long GetFilterResX() const { return m_filterResX.GetBaseVal(); }
    inline void SetFilterResX(const long n) { m_filterResX.GetBaseVal() = n; }

    inline long GetFilterResY() const { return m_filterResY.GetBaseVal(); }
    inline void SetFilterResY(const long n) { m_filterResY.GetBaseVal() = n; }

  public:
    inline char GetAnimatedFilterUnits() const { return m_filterUnits.GetAnimVal(); }
    inline void SetAnimatedFilterUnits(const char n) { m_filterUnits.GetAnimVal() = n; }

    inline char GetAnimatedPrimitiveUnits() const { return m_primitiveUnits.GetAnimVal(); }
    inline void SetAnimatedPrimitiveUnits(const char n) { m_primitiveUnits.GetAnimVal() = n; }

    inline wxSVGLength& GetAnimatedX() { return m_x.GetAnimVal(); }
    inline void SetAnimatedX(const wxSVGLength& n) { m_x.GetAnimVal() = n; }

    inline wxSVGLength& GetAnimatedY() { return m_y.GetAnimVal(); }
    inline void SetAnimatedY(const wxSVGLength& n) { m_y.GetAnimVal() = n; }

    inline wxSVGLength& GetAnimatedWidth() { return m_width.GetAnimVal(); }
    inline void SetAnimatedWidth(const wxSVGLength& n) { m_width.GetAnimVal() = n; }

    inline wxSVGLength& GetAnimatedHeight() { return m_height.GetAnimVal(); }
    inline void SetAnimatedHeight(const wxSVGLength& n) { m_height.GetAnimVal() = n; }

    inline long GetAnimatedFilterResX() const { return m_filterResX.GetAnimVal(); }
    inline void SetAnimatedFilterResX(const long n) { m_filterResX.GetAnimVal() = n; }

    inline long GetAnimatedFilterResY() const { return m_filterResY.GetAnimVal(); }
    inline void SetAnimatedFilterResY(const long n) { m_filterResY.GetAnimVal() = n; }

  public:
    wxSVGFilterElement(wxSVGDocument* doc, wxString tagName = wxT("filter")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGFilterElement() {}
    virtual void SetFilterRes(unsigned long filterResX, unsigned long filterResY);
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_FILTER_ELEMENT; }
};

#endif // WX_SVG_FILTER_ELEMENT_H
