//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEColorMatrixElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_COLOR_MATRIX_ELEMENT_H
#define WX_SVG_FE_COLOR_MATRIX_ELEMENT_H

#include "SVGElement.h"
#include "SVGFilterPrimitiveStandardAttributes.h"
#include "SVGAnimatedString.h"
#include "SVGAnimatedEnumeration.h"
#include "SVGAnimatedNumberList.h"
#include "String.h"

class wxSVGFEColorMatrixElement:
  public wxSVGElement,
  public wxSVGFilterPrimitiveStandardAttributes
{
  public:

	enum wxSVG_FECOLORMATRIX_TYPE
	{
	  wxSVG_FECOLORMATRIX_TYPE_UNKNOWN = 0,
	  wxSVG_FECOLORMATRIX_TYPE_MATRIX = 1,
	  wxSVG_FECOLORMATRIX_TYPE_SATURATE = 2,
	  wxSVG_FECOLORMATRIX_TYPE_HUEROTATE = 3,
	  wxSVG_FECOLORMATRIX_TYPE_LUMINANCETOALPHA = 4
	};

  protected:
	wxSVGAnimatedString m_in1;
	wxSVGAnimatedEnumeration m_type;
	wxSVGAnimatedNumberList m_values;

  public:
	inline wxString GetIn1() const { return m_in1.GetBaseVal(); }
	inline void SetIn1(const wxString& n) { m_in1.GetBaseVal() = n; }

	inline char GetType() const { return m_type.GetBaseVal(); }
	inline void SetType(const char n) { m_type.GetBaseVal() = n; }

	inline wxSVGNumberList& GetValues() { return m_values.GetBaseVal(); }
	inline void SetValues(const wxSVGNumberList& n) { m_values.GetBaseVal() = n; }

  public:
	inline wxString GetAnimatedIn1() const { return m_in1.GetAnimVal(); }
	inline void SetAnimatedIn1(const wxString& n) { m_in1.GetAnimVal() = n; }

	inline char GetAnimatedType() const { return m_type.GetAnimVal(); }
	inline void SetAnimatedType(const char n) { m_type.GetAnimVal() = n; }

	inline wxSVGNumberList& GetAnimatedValues() { return m_values.GetAnimVal(); }
	inline void SetAnimatedValues(const wxSVGNumberList& n) { m_values.GetAnimVal() = n; }

  public:
	wxSVGFEColorMatrixElement(wxSVGDocument* doc, wxString tagName = wxT("feColorMatrix")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGFEColorMatrixElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_FECOLORMATRIX_ELEMENT; }
};

#endif // WX_SVG_FE_COLOR_MATRIX_ELEMENT_H
