//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEMergeNodeElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_MERGE_NODE_ELEMENT_H
#define WX_SVG_FE_MERGE_NODE_ELEMENT_H

#include "SVGElement.h"
#include "SVGAnimatedString.h"
#include "String.h"

class wxSVGFEMergeNodeElement:
  public wxSVGElement
{
  protected:
    wxSVGAnimatedString m_in1;

  public:
    inline const wxString& GetIn1() { return m_in1.GetBaseVal(); }
    inline void SetIn1(const wxString& n) { m_in1.GetBaseVal() = n; }

  public:
    inline const wxString& GetAnimatedIn1() { return m_in1.GetAnimVal(); }
    inline void SetAnimatedIn1(const wxString& n) { m_in1.GetAnimVal() = n; }

  public:
    wxSVGFEMergeNodeElement(wxSVGDocument* doc, wxString tagName = wxT("feMergeNode")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGFEMergeNodeElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_FEMERGENODE_ELEMENT; }
};

#endif // WX_SVG_FE_MERGE_NODE_ELEMENT_H
