//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEFuncAElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_FUNC_A_ELEMENT_H
#define WX_SVG_FE_FUNC_A_ELEMENT_H

#include "SVGComponentTransferFunctionElement.h"
#include "String.h"

class wxSVGFEFuncAElement:
  public wxSVGComponentTransferFunctionElement
{
  public:
    wxSVGFEFuncAElement(wxSVGDocument* doc, wxString tagName = wxT("feFuncA")):
      wxSVGComponentTransferFunctionElement(doc, tagName) {}
    virtual ~wxSVGFEFuncAElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_FEFUNCA_ELEMENT; }
};

#endif // WX_SVG_FE_FUNC_A_ELEMENT_H
