//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEMergeElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_MERGE_ELEMENT_H
#define WX_SVG_FE_MERGE_ELEMENT_H

#include "SVGElement.h"
#include "SVGFilterPrimitiveStandardAttributes.h"
#include "String.h"

class wxSVGFEMergeElement:
  public wxSVGElement,
  public wxSVGFilterPrimitiveStandardAttributes
{
  public:
    wxSVGFEMergeElement(wxSVGDocument* doc, wxString tagName = wxT("feMerge")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGFEMergeElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_FEMERGE_ELEMENT; }
};

#endif // WX_SVG_FE_MERGE_ELEMENT_H
