//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFETileElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_TILE_ELEMENT_H
#define WX_SVG_FE_TILE_ELEMENT_H

#include "SVGElement.h"
#include "SVGFilterPrimitiveStandardAttributes.h"
#include "SVGAnimatedString.h"
#include "String.h"

class wxSVGFETileElement:
  public wxSVGElement,
  public wxSVGFilterPrimitiveStandardAttributes
{
  protected:
    wxSVGAnimatedString m_in1;

  public:
    inline const wxSVGAnimatedString& GetIn1() const { return m_in1; }
    inline void SetIn1(const wxSVGAnimatedString& n) { m_in1 = n; }
    inline void SetIn1(const wxString& n) { m_in1.SetBaseVal(n); }

  public:
    wxSVGFETileElement(wxSVGDocument* doc, wxString tagName = wxT("feTile")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGFETileElement() {}
    wxXmlNode* CloneNode(bool deep = true) { return new wxSVGFETileElement(*this); }
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_FETILE_ELEMENT; }
};

#endif // WX_SVG_FE_TILE_ELEMENT_H
