//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEFuncRElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_FUNC_R_ELEMENT_H
#define WX_SVG_FE_FUNC_R_ELEMENT_H

#include "SVGComponentTransferFunctionElement.h"
#include "String.h"

class wxSVGFEFuncRElement:
  public wxSVGComponentTransferFunctionElement
{
  public:
	wxSVGFEFuncRElement(wxSVGDocument* doc, wxString tagName = wxT("feFuncR")):
	  wxSVGComponentTransferFunctionElement(doc, tagName) {}
	virtual ~wxSVGFEFuncRElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_FEFUNCR_ELEMENT; }
};

#endif // WX_SVG_FE_FUNC_R_ELEMENT_H
