//////////////////////////////////////////////////////////////////////////////
// Name:        SVGGlyphElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_GLYPH_ELEMENT_H
#define WX_SVG_GLYPH_ELEMENT_H

#include "SVGElement.h"
#include "SVGStylable.h"
#include "String.h"

class wxSVGGlyphElement:
  public wxSVGElement,
  public wxSVGStylable
{
  public:
	wxSVGGlyphElement(wxSVGDocument* doc, wxString tagName = wxT("glyph")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGGlyphElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_GLYPH_ELEMENT; }
};

#endif // WX_SVG_GLYPH_ELEMENT_H
