//////////////////////////////////////////////////////////////////////////////
// Name:        SVGLangSpace.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_LANG_SPACE_H
#define WX_SVG_LANG_SPACE_H

#include "String.h"

class wxSVGLangSpace
{
  protected:
	wxString m_xmllang;
	wxString m_xmlspace;

  public:
	inline const wxString& GetXmllang() { return m_xmllang; }
	inline void SetXmllang(const wxString& n) { m_xmllang = n; }

	inline const wxString& GetXmlspace() { return m_xmlspace; }
	inline void SetXmlspace(const wxString& n) { m_xmlspace = n; }

  public:
	virtual ~wxSVGLangSpace() {}
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_LANG_SPACE_H
