//////////////////////////////////////////////////////////////////////////////
// Name:        SVGMissingGlyphElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_MISSING_GLYPH_ELEMENT_H
#define WX_SVG_MISSING_GLYPH_ELEMENT_H

#include "SVGElement.h"
#include "SVGStylable.h"
#include "String.h"

class wxSVGMissingGlyphElement:
  public wxSVGElement,
  public wxSVGStylable
{
  public:
    wxSVGMissingGlyphElement(wxSVGDocument* doc, wxString tagName = wxT("missing-glyph")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGMissingGlyphElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_MISSING_GLYPH_ELEMENT; }
};

#endif // WX_SVG_MISSING_GLYPH_ELEMENT_H
