//////////////////////////////////////////////////////////////////////////////
// Name:        SVGMPathElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_M_PATH_ELEMENT_H
#define WX_SVG_M_PATH_ELEMENT_H

#include "SVGElement.h"
#include "SVGURIReference.h"
#include "SVGExternalResourcesRequired.h"
#include "String.h"

class wxSVGMPathElement:
  public wxSVGElement,
  public wxSVGURIReference,
  public wxSVGExternalResourcesRequired
{
  public:
	wxSVGMPathElement(wxSVGDocument* doc, wxString tagName = wxT("mpath")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGMPathElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_MPATH_ELEMENT; }
};

#endif // WX_SVG_M_PATH_ELEMENT_H
