//////////////////////////////////////////////////////////////////////////////
// Name:        SVGMetadataElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_METADATA_ELEMENT_H
#define WX_SVG_METADATA_ELEMENT_H

#include "SVGElement.h"
#include "String.h"

class wxSVGMetadataElement:
  public wxSVGElement
{
  public:
    wxSVGMetadataElement(wxSVGDocument* doc, wxString tagName = wxT("metadata")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGMetadataElement() {}
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_METADATA_ELEMENT; }
};

#endif // WX_SVG_METADATA_ELEMENT_H
