//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPoint.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_POINT_H
#define WX_SVG_POINT_H

#include "SVGMatrix.h"

class wxSVGPoint
{
  protected:
	float m_x;
	float m_y;

  public:
	inline float GetX() const { return m_x; }
	inline void SetX(const float n) { m_x = n; }

	inline float GetY() const { return m_y; }
	inline void SetY(const float n) { m_y = n; }

  public:
	wxSVGPoint(): m_x(0), m_y(0) {}
	virtual ~wxSVGPoint() {}
	virtual wxSVGPoint MatrixTransform(const wxSVGMatrix& matrix);
};

#endif // WX_SVG_POINT_H
