//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPaint.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_PAINT_H
#define WX_SVG_PAINT_H

#include "SVGColor.h"
#include "String.h"

class wxSVGPaint:
  public wxSVGColor
{
  public:

	enum wxSVG_PAINTTYPE
	{
	  wxSVG_PAINTTYPE_UNKNOWN = 0,
	  wxSVG_PAINTTYPE_RGBCOLOR = 1,
	  wxSVG_PAINTTYPE_RGBCOLOR_ICCCOLOR = 2,
	  wxSVG_PAINTTYPE_NONE = 101,
	  wxSVG_PAINTTYPE_CURRENTCOLOR = 102,
	  wxSVG_PAINTTYPE_URI_NONE = 103,
	  wxSVG_PAINTTYPE_URI_CURRENTCOLOR = 104,
	  wxSVG_PAINTTYPE_URI_RGBCOLOR = 105,
	  wxSVG_PAINTTYPE_URI_RGBCOLOR_ICCCOLOR = 106,
	  wxSVG_PAINTTYPE_URI = 107
	};

  protected:
	wxSVG_PAINTTYPE m_paintType;
	wxString m_uri;

  public:
	inline wxSVG_PAINTTYPE GetPaintType() const { return m_paintType; }
	inline void SetPaintType(const wxSVG_PAINTTYPE& n) { m_paintType = n; }

	inline wxString GetUri() const { return m_uri; }
	inline void SetUri(const wxString& n) { m_uri = n; }

  public:
	wxSVGPaint(): m_paintType(wxSVG_PAINTTYPE(0)) {}
	virtual ~wxSVGPaint() {}
	virtual void SetPaint(wxSVG_PAINTTYPE paintType, const wxString& uri, const wxString& rgbColor, const wxString& iccColor);
};

#endif // WX_SVG_PAINT_H
