//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPathSegList.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genList.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_PATH_SEG_LIST_H
#define WX_SVG_PATH_SEG_LIST_H

#include "SVGPathSeg.h"
#include <wx/dynarray.h>
WX_DECLARE_OBJARRAY(wxSVGPathSeg, wxSVGPathSegList);

#endif // WX_SVG_PATH_SEG_LIST_H
