//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPathSegArcAbs.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_PATH_SEG_ARC_ABS_H
#define WX_SVG_PATH_SEG_ARC_ABS_H

#include "SVGPathSeg.h"

class wxSVGPathSegArcAbs:
  public wxSVGPathSeg
{
  protected:
    float m_x;
    float m_y;
    float m_r1;
    float m_r2;
    float m_angle;
    bool m_largeArcFlag;
    bool m_sweepFlag;

  public:
    inline float GetX() const { return m_x; }
    inline void SetX(const float n) { m_x = n; }

    inline float GetY() const { return m_y; }
    inline void SetY(const float n) { m_y = n; }

    inline float GetR1() const { return m_r1; }
    inline void SetR1(const float n) { m_r1 = n; }

    inline float GetR2() const { return m_r2; }
    inline void SetR2(const float n) { m_r2 = n; }

    inline float GetAngle() const { return m_angle; }
    inline void SetAngle(const float n) { m_angle = n; }

    inline bool GetLargeArcFlag() const { return m_largeArcFlag; }
    inline void SetLargeArcFlag(const bool n) { m_largeArcFlag = n; }

    inline bool GetSweepFlag() const { return m_sweepFlag; }
    inline void SetSweepFlag(const bool n) { m_sweepFlag = n; }

  public:
    wxSVGPathSegArcAbs():
      wxSVGPathSeg(wxPATHSEG_ARC_ABS), m_x(0), m_y(0), m_r1(0), m_r2(0), m_angle(0), m_largeArcFlag(0), m_sweepFlag(0) {}
    virtual ~wxSVGPathSegArcAbs() {}
};

#endif // WX_SVG_PATH_SEG_ARC_ABS_H
