//////////////////////////////////////////////////////////////////////////////
// Name:        SVGPointList.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by genList.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_POINT_LIST_H
#define WX_SVG_POINT_LIST_H

#include "SVGPoint.h"
#include <wx/dynarray.h>
WX_DECLARE_OBJARRAY(wxSVGPoint, wxSVGPointList);

#endif // WX_SVG_POINT_LIST_H
