//////////////////////////////////////////////////////////////////////////////
// Name:        SVGStylable.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_STYLABLE_H
#define WX_SVG_STYLABLE_H

#include "SVGAnimatedString.h"
#include "CSSStyleDeclaration.h"
#include "CSSValue.h"
#include "String.h"

class wxSVGStylable
{
  protected:
	wxSVGAnimatedString m_className;
	wxCSSStyleDeclaration m_style;
	bool SetCustomAttribute(const wxString& name, const wxString& value);

  public:
	inline wxString GetClassName() const { return m_className.GetBaseVal(); }
	inline void SetClassName(const wxString& n) { m_className.GetBaseVal() = n; }

	inline wxCSSStyleDeclaration& GetStyle() { return m_style; }
	inline void SetStyle(const wxCSSStyleDeclaration& n) { m_style = n; }

  public:
	virtual ~wxSVGStylable() {}
	inline void UpdateStyle(wxCSSStyleDeclaration& style) { style.Add(GetStyle()); }
	virtual wxCSSValue GetPresentationAttribute(const wxString& name);
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_STYLABLE_H
