//////////////////////////////////////////////////////////////////////////////
// Name:        SVGSwitchElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_SWITCH_ELEMENT_H
#define WX_SVG_SWITCH_ELEMENT_H

#include "SVGElement.h"
#include "SVGTests.h"
#include "SVGLangSpace.h"
#include "SVGExternalResourcesRequired.h"
#include "SVGStylable.h"
#include "SVGTransformable.h"
#include "EventTarget.h"
#include "String.h"

class wxSVGSwitchElement:
  public wxSVGElement,
  public wxSVGTests,
  public wxSVGLangSpace,
  public wxSVGExternalResourcesRequired,
  public wxSVGStylable,
  public wxSVGTransformable,
  public wxEventTarget
{
  public:
    wxSVGSwitchElement(wxSVGDocument* doc, wxString tagName = wxT("switch")):
      wxSVGElement(doc, tagName) {}
    virtual ~wxSVGSwitchElement() {}
    wxXmlNode* CloneNode(bool deep = true) { return new wxSVGSwitchElement(*this); }
    virtual wxSVGRect GetBBox() { return wxSVGLocatable::GetBBox(this); }
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_SWITCH_ELEMENT; }
};

#endif // WX_SVG_SWITCH_ELEMENT_H
