//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTextContentElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_TEXT_CONTENT_ELEMENT_H
#define WX_SVG_TEXT_CONTENT_ELEMENT_H

#include "SVGElement.h"
#include "SVGTests.h"
#include "SVGLangSpace.h"
#include "SVGExternalResourcesRequired.h"
#include "SVGStylable.h"
#include "EventTarget.h"
#include "SVGAnimatedLength.h"
#include "SVGAnimatedEnumeration.h"
#include "SVGPoint.h"
#include "SVGRect.h"
#include "String.h"

class wxSVGTextContentElement:
  public wxSVGElement,
  public wxSVGTests,
  public wxSVGLangSpace,
  public wxSVGExternalResourcesRequired,
  public wxSVGStylable,
  public wxEventTarget
{
  public:

	enum wxLENGTHADJUST
	{
	  wxLENGTHADJUST_UNKNOWN = 0,
	  wxLENGTHADJUST_SPACING = 1,
	  wxLENGTHADJUST_SPACINGANDGLYPHS = 2
	};

  protected:
	wxSVGAnimatedLength m_textLength;
	wxSVGAnimatedEnumeration m_lengthAdjust;

  public:
	inline wxSVGLength& GetTextLength() { return m_textLength.GetBaseVal(); }
	inline void SetTextLength(const wxSVGLength& n) { m_textLength.GetBaseVal() = n; }

	inline char GetLengthAdjust() const { return m_lengthAdjust.GetBaseVal(); }
	inline void SetLengthAdjust(const char n) { m_lengthAdjust.GetBaseVal() = n; }

  public:
	inline wxSVGLength& GetAnimatedTextLength() { return m_textLength.GetAnimVal(); }
	inline void SetAnimatedTextLength(const wxSVGLength& n) { m_textLength.GetAnimVal() = n; }

	inline char GetAnimatedLengthAdjust() const { return m_lengthAdjust.GetAnimVal(); }
	inline void SetAnimatedLengthAdjust(const char n) { m_lengthAdjust.GetAnimVal() = n; }

  public:
	wxSVGTextContentElement(wxSVGDocument* doc, wxString tagName = wxT("")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGTextContentElement() {}
	virtual long GetNumberOfChars();
	virtual float GetComputedTextLength();
	virtual float GetSubStringLength(unsigned long charnum, unsigned long nchars);
	virtual wxSVGPoint GetStartPositionOfChar(unsigned long charnum);
	virtual wxSVGPoint GetEndPositionOfChar(unsigned long charnum);
	virtual wxSVGRect GetExtentOfChar(unsigned long charnum);
	virtual float GetRotationOfChar(unsigned long charnum);
	virtual long GetCharNumAtPosition(const wxSVGPoint& point);
	virtual void SelectSubString(unsigned long charnum, unsigned long nchars);
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_TEXT_CONTENT_ELEMENT_H
