//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTextPositioningElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_TEXT_POSITIONING_ELEMENT_H
#define WX_SVG_TEXT_POSITIONING_ELEMENT_H

#include "SVGTextContentElement.h"
#include "SVGAnimatedLengthList.h"
#include "SVGAnimatedNumberList.h"
#include "String.h"

class wxSVGTextPositioningElement:
  public wxSVGTextContentElement
{
  protected:
	wxSVGAnimatedLengthList m_x;
	wxSVGAnimatedLengthList m_y;
	wxSVGAnimatedLengthList m_dx;
	wxSVGAnimatedLengthList m_dy;
	wxSVGAnimatedNumberList m_rotate;

  public:
	inline wxSVGLengthList& GetX() { return m_x.GetBaseVal(); }
	inline void SetX(const wxSVGLengthList& n) { m_x.GetBaseVal() = n; }

	inline wxSVGLengthList& GetY() { return m_y.GetBaseVal(); }
	inline void SetY(const wxSVGLengthList& n) { m_y.GetBaseVal() = n; }

	inline wxSVGLengthList& GetDx() { return m_dx.GetBaseVal(); }
	inline void SetDx(const wxSVGLengthList& n) { m_dx.GetBaseVal() = n; }

	inline wxSVGLengthList& GetDy() { return m_dy.GetBaseVal(); }
	inline void SetDy(const wxSVGLengthList& n) { m_dy.GetBaseVal() = n; }

	inline wxSVGNumberList& GetRotate() { return m_rotate.GetBaseVal(); }
	inline void SetRotate(const wxSVGNumberList& n) { m_rotate.GetBaseVal() = n; }

  public:
	inline wxSVGLengthList& GetAnimatedX() { return m_x.GetAnimVal(); }
	inline void SetAnimatedX(const wxSVGLengthList& n) { m_x.GetAnimVal() = n; }

	inline wxSVGLengthList& GetAnimatedY() { return m_y.GetAnimVal(); }
	inline void SetAnimatedY(const wxSVGLengthList& n) { m_y.GetAnimVal() = n; }

	inline wxSVGLengthList& GetAnimatedDx() { return m_dx.GetAnimVal(); }
	inline void SetAnimatedDx(const wxSVGLengthList& n) { m_dx.GetAnimVal() = n; }

	inline wxSVGLengthList& GetAnimatedDy() { return m_dy.GetAnimVal(); }
	inline void SetAnimatedDy(const wxSVGLengthList& n) { m_dy.GetAnimVal() = n; }

	inline wxSVGNumberList& GetAnimatedRotate() { return m_rotate.GetAnimVal(); }
	inline void SetAnimatedRotate(const wxSVGNumberList& n) { m_rotate.GetAnimVal() = n; }

  public:
	wxSVGTextPositioningElement(wxSVGDocument* doc, wxString tagName = wxT("")):
	  wxSVGTextContentElement(doc, tagName) {}
	virtual ~wxSVGTextPositioningElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_TEXT_POSITIONING_ELEMENT_H
