//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTitleElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_TITLE_ELEMENT_H
#define WX_SVG_TITLE_ELEMENT_H

#include "SVGElement.h"
#include "SVGLangSpace.h"
#include "SVGStylable.h"
#include "String.h"

class wxSVGTitleElement:
  public wxSVGElement,
  public wxSVGLangSpace,
  public wxSVGStylable
{
  public:
	wxSVGTitleElement(wxSVGDocument* doc, wxString tagName = wxT("title")):
	  wxSVGElement(doc, tagName) {}
	virtual ~wxSVGTitleElement() {}
	bool SetAttribute(const wxString& name, const wxString& value);
	virtual const wxSVGDTD GetDtd() const { return wxSVG_TITLE_ELEMENT; }
};

#endif // WX_SVG_TITLE_ELEMENT_H
