//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTests.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_TESTS_H
#define WX_SVG_TESTS_H

#include "SVGStringList.h"
#include "String.h"

class wxSVGTests
{
  protected:
	wxSVGStringList m_requiredFeatures;
	wxSVGStringList m_requiredExtensions;
	wxSVGStringList m_systemLanguage;

  public:
	inline wxSVGStringList& GetRequiredFeatures() { return m_requiredFeatures; }
	inline void SetRequiredFeatures(const wxSVGStringList& n) { m_requiredFeatures = n; }

	inline wxSVGStringList& GetRequiredExtensions() { return m_requiredExtensions; }
	inline void SetRequiredExtensions(const wxSVGStringList& n) { m_requiredExtensions = n; }

	inline wxSVGStringList& GetSystemLanguage() { return m_systemLanguage; }
	inline void SetSystemLanguage(const wxSVGStringList& n) { m_systemLanguage = n; }

  public:
	virtual ~wxSVGTests() {}
	virtual bool HasExtension(const wxString& extension);
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_TESTS_H
