//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTransformable.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_TRANSFORMABLE_H
#define WX_SVG_TRANSFORMABLE_H

#include "SVGLocatable.h"
#include "SVGAnimatedTransformList.h"
#include "String.h"

class wxSVGTransformable:
  public wxSVGLocatable
{
  protected:
	wxSVGAnimatedTransformList m_transform;

  public:
	inline wxSVGTransformList& GetTransform() { return m_transform.GetBaseVal(); }
	inline void SetTransform(const wxSVGTransformList& n) { m_transform.GetBaseVal() = n; }

  public:
	inline wxSVGTransformList& GetAnimatedTransform() { return m_transform.GetAnimVal(); }
	inline void SetAnimatedTransform(const wxSVGTransformList& n) { m_transform.GetAnimVal() = n; }

  public:
	virtual ~wxSVGTransformable() {}
	void UpdateMatrix(wxSVGMatrix& matrix);
	bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_TRANSFORMABLE_H
