//////////////////////////////////////////////////////////////////////////////
// Name:        SVGURIReference.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_URI_REFERENCE_H
#define WX_SVG_URI_REFERENCE_H

#include "SVGAnimatedString.h"
#include "String.h"

class wxSVGURIReference
{
  protected:
    wxSVGAnimatedString m_href;

  public:
    inline const wxString& GetHref() { return m_href.GetBaseVal(); }
    inline void SetHref(const wxString& n) { m_href.GetBaseVal() = n; }

  public:
    inline const wxString& GetAnimatedHref() { return m_href.GetAnimVal(); }
    inline void SetAnimatedHref(const wxString& n) { m_href.GetAnimVal() = n; }

  public:
    virtual ~wxSVGURIReference() {}
    bool SetAttribute(const wxString& name, const wxString& value);
};

#endif // WX_SVG_URI_REFERENCE_H
