//////////////////////////////////////////////////////////////////////////////
// Name:        SVGVKernElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_V_KERN_ELEMENT_H
#define WX_SVG_V_KERN_ELEMENT_H

#include "SVGElement.h"
#include "String.h"

class wxSVGVKernElement:
  public wxSVGElement
{
  public:
    wxSVGVKernElement(wxString tagName = wxT("vkern")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGVKernElement() {}
    wxXmlNode* CloneNode(bool deep = true) { return new wxSVGVKernElement(*this); }
    bool HasAttribute(const wxString& name);
    wxString GetAttribute(const wxString& name);
    bool SetAttribute(const wxString& name, const wxString& value);
    virtual const wxSVGDTD GetDtd() const { return wxSVG_VKERN_ELEMENT; }
};

#endif // WX_SVG_V_KERN_ELEMENT_H
